version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "15:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
      include: scope
    groups:
      symfony:
        patterns:
          - "symfony/*"
