version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "15:20"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    groups:
      symfony:
        patterns:
          - "symfony/*"
