version: 2.1

workflows:
  testing:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run: composer validate --no-check-publish -n
      - run: composer install -n --prefer-dist --no-progress --no-suggest
      
